# coding: utf-8

# flake8: noqa

"""
    Device Connect

    API for managing persistent device connections. Intended for use by the web GUI   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from management_api.api.management_api_client import ManagementAPIClient

# import ApiClient
from management_api.api_client import ApiClient
from management_api.configuration import Configuration
from management_api.exceptions import OpenApiException
from management_api.exceptions import ApiTypeError
from management_api.exceptions import ApiValueError
from management_api.exceptions import ApiKeyError
from management_api.exceptions import ApiException
# import models into sdk package
from management_api.models.device_state import DeviceState
from management_api.models.error import Error

