# coding: utf-8

# flake8: noqa
"""
    Device Connect

    Internal API for managing persistent device connections. Intended for use by the web GUI.   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from internal_api.models.error import Error
from internal_api.models.inline_object import InlineObject
from internal_api.models.inline_object1 import InlineObject1
