# Copyright 2021 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# coding: utf-8

"""
    Device Connect

    Internal API for managing persistent device connections. Intended for use by the web GUI.   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import internal_api
from internal_api.api.internal_api_client import InternalAPIClient  # noqa: E501
from internal_api.rest import ApiException


class TestInternalAPIClient(unittest.TestCase):
    """InternalAPIClient unit test stubs"""

    def setUp(self):
        self.api = internal_api.api.internal_api_client.InternalAPIClient()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_health(self):
        """Test case for check_health

        Get health status of service  # noqa: E501
        """
        pass

    def test_check_liveliness(self):
        """Test case for check_liveliness

        Get service liveliness status.  # noqa: E501
        """
        pass

    def test_decomission_device(self):
        """Test case for decomission_device

        Remove a device from the deviceconnect service.  # noqa: E501
        """
        pass

    def test_provision_device(self):
        """Test case for provision_device

        Register a new device with the deviceconnect service.  # noqa: E501
        """
        pass

    def test_provision_tenant(self):
        """Test case for provision_tenant

        Initialize internal state for a new tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
