// Copyright 2020 Northern.tech AS
//
//    All Rights Reserved

// Code generated by mockery v2.2.2. DO NOT EDIT.

package mocks

import (
	context "context"

	workflows "github.com/mendersoftware/deviceconnect/client/workflows"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *Client) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubmitAuditLog provides a mock function with given fields: ctx, log
func (_m *Client) SubmitAuditLog(ctx context.Context, log workflows.AuditLog) error {
	ret := _m.Called(ctx, log)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, workflows.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
