# coding: utf-8

"""
    Device Connect

    API for managing persistent device connections. Intended for use by the web GUI   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import management_api
from management_api.models.device_state import DeviceState  # noqa: E501
from management_api.rest import ApiException

class TestDeviceState(unittest.TestCase):
    """DeviceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DeviceState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = management_api.models.device_state.DeviceState()  # noqa: E501
        if include_optional :
            return DeviceState(
                device_id = '0', 
                status = 'connected'
            )
        else :
            return DeviceState(
        )

    def testDeviceState(self):
        """Test DeviceState"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
