# coding: utf-8

"""
    Device Connect

    Device facing API for managing persistent device connections.   # noqa: E501

    The version of the OpenAPI document: 1
    Contact: support@mender.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import devices_api
from devices_api.api.devices_api_client import DevicesAPIClient  # noqa: E501
from devices_api.rest import ApiException


class TestDevicesAPIClient(unittest.TestCase):
    """DevicesAPIClient unit test stubs"""

    def setUp(self):
        self.api = devices_api.api.devices_api_client.DevicesAPIClient()  # noqa: E501

    def tearDown(self):
        pass

    def test_connect(self):
        """Test case for connect

        Connect the device and make it available to the server.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
