// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

// Verify provides a mock function with given fields: ctx, token, method, uri
func (_m *ClientInterface) Verify(ctx context.Context, token string, method string, uri string) error {
	ret := _m.Called(ctx, token, method, uri)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, token, method, uri)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
