openapi: 3.0.3

info:
  title: Device connect
  description: |
    Internal API for managing persistent device connections.
    Intended for use by the web GUI.
  version: "1"

  contact:
    name: Mender Support
    email: support@mender.io
    url: https://mender.io/contact-us

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://mender-deviceconnect:8080/api/internal/v1/deviceconnect

tags:
  - name: InternalAPI

paths:
  /health:
    get:
      tags:
        - InternalAPI
      summary: Get health status of service
      operationId: Check Health
      responses:
        204:
          description: Service is healthy.
        400:
          description: Invalid Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /alive:
    get:
      tags:
        - InternalAPI
      summary: Get service liveliness status.
      operationId: Check Liveliness
      responses:
        204:
          description: Service is up and serving requests.
        500:
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tenants:
    post:
      tags:
        - InternalAPI
      operationId: Provision tenant
      summary: Initialize internal state for a new tenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTenant'
      responses:
        201:
          description: Tenant initialized successfully.
        400:
          $ref: '#/components/responses/InvalidRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'

  /tenants/{tenantId}/devices:
    post:
      tags:
        - InternalAPI
      operationId: Provision device
      summary: Register a new device with the deviceconnect service.
      parameters:
        - in: path
          name: tenantId
          schema:
            type: string
          required: true
          description: ID of tenant the device belongs to.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        201:
          description: Device was provisioned successfully.
        400:
          $ref: '#/components/responses/InvalidRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'

  /tenants/{tenantId}/devices/{deviceId}:
    delete:
      tags:
        - InternalAPI
      operationId: Decomission device
      summary: Remove a device from the deviceconnect service.
      parameters:
        - in: path
          name: tenantId
          schema:
            type: string
          required: true
          description: ID of tenant the device belongs to.
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
          description: ID of the target device.
      responses:
        202:
          description: Device was deleted successfully
        500:
          $ref: '#/components/responses/InternalServerError'


components:

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description:
            Request ID passed with the request X-MEN-RequestID header
            or generated by the server.
      description: Error descriptor.
      example:
        error: "<error description>"
        request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    NewTenant:
      type: object
      properties:
        tenant_id:
          type: string
          description: ID of new tenant.
      required:
        - tenant_id

    Device:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
          description: ID of the new device.
      required:
        - device_id


  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "internal error"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    InvalidRequestError:
      description: Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "bad request parameters"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"
